/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            fontFamily: {
                display: ['"Fredoka"', '"Baloo 2"', 'system-ui', 'sans-serif'],
                body: ['"Nunito"', 'system-ui', 'sans-serif'],
            },
            colors: {
                sky: {
                    50: '#e0f7ff',
                    100: '#b3e5ff',
                    200: '#81d4fa',
                    300: '#4fc3f7',
                    400: '#29b6f6',
                    500: '#03a9f4',
                    600: '#039be5',
                    700: '#0288d1',
                },
                blush: {
                    50: '#ffe4ed',
                    100: '#ffccdd',
                    200: '#ffaacc',
                    300: '#ff88bb',
                    400: '#ff5599',
                    500: '#ff1493',
                    600: '#e60580',
                    700: '#cc046b',
                },
                mint: {
                    50: '#c8f8e4',
                    100: '#a5f3d0',
                    200: '#82ecbb',
                    300: '#5fe5a7',
                    400: '#3cde92',
                    500: '#1ad7d7',
                    600: '#00bfa5',
                    700: '#00a899',
                },
                lemon: {
                    50: '#fffef0',
                    100: '#fffde0',
                    200: '#fffcc2',
                    300: '#fffaa3',
                    400: '#fff885',
                    500: '#ffd600',
                    600: '#ffb300',
                    700: '#ff8c00',
                },
                lavender: {
                    50: '#f3e5f5',
                    100: '#e1bee7',
                    200: '#ce93d8',
                    300: '#ba68c8',
                    400: '#ab47bc',
                    500: '#9c27b0',
                    600: '#8e24aa',
                    700: '#7b1fa2',
                },
                peach: {
                    50: '#ffe0cc',
                    100: '#ffccb3',
                    200: '#ffb39a',
                    300: '#ff9a80',
                    400: '#ff8a65',
                    500: '#ff7043',
                    600: '#ff5722',
                    700: '#e64a19',
                },
                coral: {
                    50: '#ffe5da',
                    100: '#ffccb3',
                    200: '#ffb39a',
                    300: '#ff9a80',
                    400: '#ff8a65',
                    500: '#ff6b5b',
                    600: '#ff4d2d',
                    700: '#ff3300',
                },
                sunny: {
                    50: '#fff9e6',
                    100: '#fff4cc',
                    200: '#ffee99',
                    300: '#ffe966',
                    400: '#ffe333',
                    500: '#ffdd00',
                    600: '#ffc400',
                    700: '#ffab00',
                },
                ocean: {
                    50: '#e1f5fe',
                    100: '#b3e5fc',
                    200: '#81d4fa',
                    300: '#4fc3f7',
                    400: '#29b6f6',
                    500: '#03a9f4',
                    600: '#0398d8',
                    700: '#0288d1',
                },
                forest: {
                    50: '#e8f5e9',
                    100: '#c8e6c9',
                    200: '#a5d6a7',
                    300: '#81c784',
                    400: '#66bb6a',
                    500: '#4caf50',
                    600: '#43a047',
                    700: '#388e3c',
                },
                cream: '#fffbf5',
            },
            borderRadius: {
                '4xl': '2rem',
                '5xl': '2.5rem',
                '6xl': '3rem',
            },
            boxShadow: {
                soft: '0 8px 32px -8px rgba(120, 100, 160, 0.15)',
                'soft-lg': '0 20px 60px -15px rgba(120, 100, 160, 0.22)',
                glow: '0 0 30px rgba(157, 124, 230, 0.3)',
                'inner-soft': 'inset 0 2px 8px rgba(255, 255, 255, 0.6)',
                card: '0 4px 24px -6px rgba(120, 100, 160, 0.12)',
                'card-hover': '0 16px 48px -10px rgba(120, 100, 160, 0.28)',
            },
            transitionTimingFunction: {
                'bounce-soft': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
                'smooth-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
            },
            keyframes: {
                float: {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-14px)' },
                },
                'float-slow': {
                    '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
                    '50%': { transform: 'translateY(-22px) translateX(10px)' },
                },
                twinkle: {
                    '0%, 100%': { opacity: '0.3', transform: 'scale(0.8)' },
                    '50%': { opacity: '1', transform: 'scale(1.15)' },
                },
                wiggle: {
                    '0%, 100%': { transform: 'rotate(-3deg)' },
                    '50%': { transform: 'rotate(3deg)' },
                },
                'gradient-shift': {
                    '0%, 100%': { backgroundPosition: '0% 50%' },
                    '50%': { backgroundPosition: '100% 50%' },
                },
                'pop-in': {
                    '0%': { transform: 'scale(0.8)', opacity: '0' },
                    '60%': { transform: 'scale(1.05)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                'slide-up': {
                    '0%': { transform: 'translateY(20px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                'fade-in': {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                'bounce-in': {
                    '0%': { transform: 'scale(0.3)', opacity: '0' },
                    '50%': { transform: 'scale(1.1)' },
                    '70%': { transform: 'scale(0.95)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                'shimmer': {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
                'wiggle-soft': {
                    '0%, 100%': { transform: 'rotate(0deg)' },
                    '25%': { transform: 'rotate(-2deg)' },
                    '75%': { transform: 'rotate(2deg)' },
                },
                'spin-slow': {
                    from: { transform: 'rotate(0deg)' },
                    to: { transform: 'rotate(360deg)' },
                },
                'pulse-soft': {
                    '0%, 100%': { transform: 'scale(1)', opacity: '1' },
                    '50%': { transform: 'scale(1.06)', opacity: '0.85' },
                },
                'drift-x': {
                    '0%': { transform: 'translateX(-10%)' },
                    '100%': { transform: 'translateX(110%)' },
                },
                'bounce-up': {
                    '0%': { transform: 'translateY(0)' },
                    '25%': { transform: 'translateY(-10px)' },
                    '50%': { transform: 'translateY(0)' },
                    '75%': { transform: 'translateY(-5px)' },
                    '100%': { transform: 'translateY(0)' },
                },
                'spin-y': {
                    '0%': { transform: 'rotateY(0deg) scale(1)' },
                    '50%': { transform: 'rotateY(180deg) scale(1.05)' },
                    '100%': { transform: 'rotateY(360deg) scale(1)' },
                },
                'pulse-ring': {
                    '0%': { transform: 'scale(0.95)', opacity: '1' },
                    '50%': { transform: 'scale(1.05)', opacity: '0.7' },
                    '100%': { transform: 'scale(0.95)', opacity: '1' },
                },
                'rainbow': {
                    '0%': { filter: 'hue-rotate(0deg)' },
                    '25%': { filter: 'hue-rotate(90deg)' },
                    '50%': { filter: 'hue-rotate(180deg)' },
                    '75%': { filter: 'hue-rotate(270deg)' },
                    '100%': { filter: 'hue-rotate(360deg)' },
                },
                'rotate-in': {
                    '0%': { transform: 'rotateZ(-180deg) scale(0)', opacity: '0' },
                    '60%': { transform: 'rotateZ(10deg) scale(1.05)' },
                    '100%': { transform: 'rotateZ(0) scale(1)', opacity: '1' },
                },
                'shake': {
                    '0%, 100%': { transform: 'translateX(0)' },
                    '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-2px)' },
                    '20%, 40%, 60%, 80%': { transform: 'translateX(2px)' },
                },
                'heart-pulse': {
                    '0%': { transform: 'scale(1)' },
                    '25%': { transform: 'scale(1.15)' },
                    '50%': { transform: 'scale(1)' },
                    '75%': { transform: 'scale(1.15)' },
                    '100%': { transform: 'scale(1)' },
                },
                'flip': {
                    '0%': { transform: 'rotateX(0deg)' },
                    '100%': { transform: 'rotateX(360deg)' },
                },
                'slide-right': {
                    '0%': { transform: 'translateX(-100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                'glow-pulse': {
                    '0%, 100%': { boxShadow: '0 0 5px rgba(255, 215, 0, 0.4)' },
                    '50%': { boxShadow: '0 0 20px rgba(255, 215, 0, 0.8)' },
                },
            },
            animation: {
                float: 'float 6s ease-in-out infinite',
                'float-slow': 'float-slow 9s ease-in-out infinite',
                twinkle: 'twinkle 3s ease-in-out infinite',
                wiggle: 'wiggle 2.5s ease-in-out infinite',
                'gradient-shift': 'gradient-shift 8s ease infinite',
                'pop-in': 'pop-in 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) both',
                'slide-up': 'slide-up 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
                'fade-in': 'fade-in 0.3s ease-out both',
                'bounce-in': 'bounce-in 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) both',
                'shimmer': 'shimmer 2s linear infinite',
                'wiggle-soft': 'wiggle-soft 0.5s ease-in-out',
                'spin-slow': 'spin-slow 20s linear infinite',
                'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
                'drift-x': 'drift-x 30s linear infinite',
                'bounce-up': 'bounce-up 1.2s ease-in-out infinite',
                'spin-y': 'spin-y 2s ease-in-out infinite',
                'pulse-ring': 'pulse-ring 1.5s ease-in-out infinite',
                'rainbow': 'rainbow 6s linear infinite',
                'rotate-in': 'rotate-in 0.8s cubic-bezier(0.34, 1.56, 0.64, 1) both',
                'shake': 'shake 0.4s ease-in-out',
                'heart-pulse': 'heart-pulse 1.2s ease-in-out infinite',
                'flip': 'flip 2s ease-in-out infinite',
                'slide-right': 'slide-right 0.5s cubic-bezier(0.16, 1, 0.3, 1) both',
                'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
            },
        },
    },
    plugins: [],
};